FROM postgis/postgis:15-3.4-alpine

# Install build dependencies, build pgvector, and clean up
RUN apk add --no-cache --virtual .build-deps \
    git \
    make \
    gcc \
    musl-dev \
    postgresql15-dev \
    clang15 \
    llvm15 \
    && cd /tmp \
    && git clone --branch v0.5.1 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install \
    && rm -rf /tmp/pgvector \
    && apk del .build-deps
