/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'rgb(var(--color-primary-50-rgb) / <alpha-value>)',
          100: 'rgb(var(--color-primary-100-rgb) / <alpha-value>)',
          200: 'rgb(var(--color-primary-200-rgb) / <alpha-value>)',
          300: 'rgb(var(--color-primary-300-rgb) / <alpha-value>)',
          400: 'rgb(var(--color-primary-400-rgb) / <alpha-value>)',
          500: 'rgb(var(--color-primary-500-rgb) / <alpha-value>)',
          600: 'rgb(var(--color-primary-600-rgb) / <alpha-value>)',
          700: 'rgb(var(--color-primary-700-rgb) / <alpha-value>)',
          800: 'rgb(var(--color-primary-800-rgb) / <alpha-value>)',
          900: 'rgb(var(--color-primary-900-rgb) / <alpha-value>)',
        },
        secondary: {
          50: 'rgb(var(--color-secondary-50-rgb) / <alpha-value>)',
          100: 'rgb(var(--color-secondary-100-rgb) / <alpha-value>)',
          200: 'rgb(var(--color-secondary-200-rgb) / <alpha-value>)',
          300: 'rgb(var(--color-secondary-300-rgb) / <alpha-value>)',
          400: 'rgb(var(--color-secondary-400-rgb) / <alpha-value>)',
          500: 'rgb(var(--color-secondary-500-rgb) / <alpha-value>)',
          600: 'rgb(var(--color-secondary-600-rgb) / <alpha-value>)',
          700: 'rgb(var(--color-secondary-700-rgb) / <alpha-value>)',
          800: 'rgb(var(--color-secondary-800-rgb) / <alpha-value>)',
          900: 'rgb(var(--color-secondary-900-rgb) / <alpha-value>)',
        },
        accent: {
          50: 'rgb(var(--color-accent-50-rgb) / <alpha-value>)',
          100: 'rgb(var(--color-accent-100-rgb) / <alpha-value>)',
          200: 'rgb(var(--color-accent-200-rgb) / <alpha-value>)',
          300: 'rgb(var(--color-accent-300-rgb) / <alpha-value>)',
          400: 'rgb(var(--color-accent-400-rgb) / <alpha-value>)',
          500: 'rgb(var(--color-accent-500-rgb) / <alpha-value>)',
          600: 'rgb(var(--color-accent-600-rgb) / <alpha-value>)',
          700: 'rgb(var(--color-accent-700-rgb) / <alpha-value>)',
          800: 'rgb(var(--color-accent-800-rgb) / <alpha-value>)',
          900: 'rgb(var(--color-accent-900-rgb) / <alpha-value>)',
        },
        error: {
          50: 'rgb(var(--color-error-50-rgb) / <alpha-value>)',
          100: 'rgb(var(--color-error-100-rgb) / <alpha-value>)',
          200: 'rgb(var(--color-error-200-rgb) / <alpha-value>)',
          300: 'rgb(var(--color-error-300-rgb) / <alpha-value>)',
          400: 'rgb(var(--color-error-400-rgb) / <alpha-value>)',
          500: 'rgb(var(--color-error-500-rgb) / <alpha-value>)',
          600: 'rgb(var(--color-error-600-rgb) / <alpha-value>)',
          700: 'rgb(var(--color-error-700-rgb) / <alpha-value>)',
          800: 'rgb(var(--color-error-800-rgb) / <alpha-value>)',
          900: 'rgb(var(--color-error-900-rgb) / <alpha-value>)',
        },
        'theme-bg': {
          primary: 'rgb(var(--color-bg-primary-rgb) / <alpha-value>)',
          secondary: 'rgb(var(--color-bg-secondary-rgb) / <alpha-value>)',
          card: 'rgb(var(--color-bg-card-rgb) / <alpha-value>)',
        },
        surface: '#0c1324',
        'on-surface': '#dce1fb',
        'on-surface-variant': '#b9caca',
        'primary-container': '#00f5ff',
        'on-primary-container': '#006c71',
        'secondary-container': '#7000ff',
        'on-secondary-container': '#ddcdff',
        'tertiary-container': '#dddddd',
        'on-tertiary-container': '#606162',
        outline: '#849495',
        'outline-variant': '#3a494a',
        cyber: {
          DEFAULT: '#00f5ff',
          dark: '#006c71',
          light: '#a3f3ff',
          hover: '#00dce5',
        },
        status: {
          success: '#10b981',
          warning: '#f59e0b',
          error: '#ef4444',
          info: '#3b82f6',
        },
        chart: {
          green: '#22c55e',
          blue: '#3b82f6',
          purple: '#8b5cf6',
          cyber: '#4fd1c5',
          gray: '#9ca3af',
        },
        map: {
          bg: '#1f2937',
          border: '#374151',
          text: '#d1d5db',
          lightBg: '#f3f4f6',
          lightText: '#374151',
          cyberBg: '#010101',
          cyberBorder: '#00ffff',
        },
      },
      borderRadius: {
        card: 'var(--radius-card)',
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: 'var(--radius-card)',
        xl: '0.75rem',
        '2xl': 'var(--radius-card)',
        '3xl': 'var(--radius-card)',
        full: '9999px',
      },
      boxShadow: {
        premium: 'var(--shadow-premium)',
        xl: 'var(--shadow-premium)',
        '2xl': 'var(--shadow-premium)',
        neon: '0 0 15px rgba(0, 245, 255, 0.3)',
        'glow-success': '0 0 10px rgba(16, 185, 129, 0.5)',
        'glow-warning': '0 0 10px rgba(245, 158, 11, 0.5)',
        'glow-error': '0 0 10px rgba(239, 68, 68, 0.5)',
        'glow-primary': '0 0 20px rgba(34, 211, 238, 0.2)',
        'glow-cyber': '0 0 30px rgba(79, 209, 197, 0.1)',
        'map-shadow': '0 4px 6px rgba(0,0,0,0.3)',
        'map-shadow-md': '0 8px 12px rgba(0,0,0,0.4)',
        'map-shadow-lg': '0 12px 20px rgba(0,0,0,0.5)',
      },
      fontSize: {
        micro: '9px',
        xxs: '10px',
        'xs-plus': '11px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Space Grotesk', 'sans-serif'],
      },
      spacing: {
        gutter: '24px',
        margin: '32px',
        md: '24px',
        xs: '4px',
        xl: '80px',
        sm: '12px',
        'container-max': '1440px',
        base: '8px',
        lg: '48px',
      },

      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
