const fs = require('fs');
const FILE_PATH = './src/lib/i18n.ts';

let content = fs.readFileSync(FILE_PATH, 'utf-8');

const languages = [
  'en',
  'sw',
  'fr',
  'pt',
  'es',
  'oro',
  'lug',
  'zu',
  'it',
  'de',
  'nl',
  'da',
  'pl',
  'hu',
  'tr',
  'ar',
  'zh',
  'hi',
  'ru',
  'uk',
  'ro',
  'cs',
  'sk',
  'bg',
  'el',
];

const TRANSLATIONS = {
  sw: {
    visits_schedule_new: 'Ratibu Ziara Mpya',
    reports_generate_new: 'Toa Ripoti Mpya',
    reports_description_prefix: 'Uchambuzi wa kina wa ',
    reports_description_suffix: ' mienendo na vipimo vya utendaji kwa kipindi cha sasa.',
    knowledge_thinking: 'Inafikiria...',
    ai_ask_button: 'Uliza AI',
    theme_choose: 'Chagua Mandhari',
    theme_select_aesthetic: 'Chagua urembo wa kilimo',
    theme_close: 'Funga',
    usage_init_title: 'Anzisha Udhibiti wa Misheni',
    usage_init_desc: 'Fungua uwezo mkubwa wa AI na SMS kwa kuchagua mpango wa kutumwa.',
    usage_realtime_telemetry: 'Telemetry ya Muda Halisi',
    usage_critical_threshold: 'Kikomo Muhimu',
    action_chat: 'Mazungumzo',
    action_sms: 'SMS',
    action_call: 'Piga Simu',
    action_video: 'Video',
    farmer_vital_score: 'Alama Muhimu',
    visit_no_history: 'Hakuna historia ya ziara iliyopatikana',
    visit_routine_inspection: 'Ukaguzi wa kawaida wa shamba na tathmini ya afya ya udongo.',
    visit_next_scheduled: 'Imeratibiwa Inayofuata',
    action_start_synthesis: 'Anza Usanisi',
    map_type: 'Aina ya Ramani',
    map_legend: 'Ramani ya Mazao',
    map_search_placeholder: 'Tafuta wakulima...',
    map_locate_me: 'Nitambue',
    map_reset_view: 'Weka upya Mtazamo',
    map_toggle_stats: 'Badili Takwimu',
    map_overview: 'Muhtasari',
    map_farms: 'Mashamba',
    map_hectares: 'Hekta',
    map_top_crops: 'Mazao ya Juu',
    farmer_active_since: 'Amekuwa Hai Tangu',
    farmer_est_yield: 'Mavuno ya Makadirio',
    farmer_farm_size: 'Ukubwa wa Shamba',
  },
  fr: {
    visits_schedule_new: 'Planifier une nouvelle visite',
    reports_generate_new: 'Générer un nouveau rapport',
    reports_description_prefix: 'Analyse approfondie de ',
    reports_description_suffix:
      ' tendances et indicateurs de performance pour la période actuelle.',
    knowledge_thinking: 'En réflexion...',
    ai_ask_button: "Demander à l'IA",
    theme_choose: 'Choisir un thème',
    theme_select_aesthetic: 'Sélectionnez une esthétique agricole',
    theme_close: 'Fermer',
    usage_init_title: 'Initialiser le contrôle de mission',
    usage_init_desc:
      "Débloquez de puissantes capacités d'IA et de SMS en sélectionnant un plan de déploiement.",
    usage_realtime_telemetry: 'Télémétrie en temps réel',
    usage_critical_threshold: 'Seuil critique',
    action_chat: 'Chat',
    action_sms: 'SMS',
    action_call: 'Appeler',
    action_video: 'Vidéo',
    farmer_vital_score: 'Score vital',
    visit_no_history: 'Aucun historique de visite trouvé',
    visit_routine_inspection: 'Inspection de routine de la ferme et évaluation de la santé du sol.',
    visit_next_scheduled: 'Prochaine visite prévue',
    action_start_synthesis: 'Commencer la synthèse',
    map_type: 'Type de carte',
    map_legend: 'Légende des cultures',
    map_search_placeholder: 'Rechercher des agriculteurs...',
    map_locate_me: 'Me localiser',
    map_reset_view: 'Réinitialiser la vue',
    map_toggle_stats: 'Basculer les statistiques',
    map_overview: 'Aperçu',
    map_farms: 'Fermes',
    map_hectares: 'Hectares',
    map_top_crops: 'Principales cultures',
    farmer_active_since: 'Actif depuis',
    farmer_est_yield: 'Rendement estimé',
    farmer_farm_size: 'Taille de la ferme',
  },
  es: {
    visits_schedule_new: 'Programar nueva visita',
    reports_generate_new: 'Generar nuevo informe',
    reports_description_prefix: 'Análisis exhaustivo de ',
    reports_description_suffix: ' tendencias y métricas de rendimiento para el período actual.',
    knowledge_thinking: 'Pensando...',
    ai_ask_button: 'Consultar IA',
    theme_choose: 'Elegir tema',
    theme_select_aesthetic: 'Seleccione una estética agrícola',
    theme_close: 'Cerrar',
    usage_init_title: 'Inicializar control de misión',
    usage_init_desc:
      'Desbloquee potentes capacidades de IA y SMS seleccionando un plan de despliegue.',
    usage_realtime_telemetry: 'Telemetría en tiempo real',
    usage_critical_threshold: 'Umbral crítico',
    action_chat: 'Chat',
    action_sms: 'SMS',
    action_call: 'Llamar',
    action_video: 'Video',
    farmer_vital_score: 'Puntuación vital',
    visit_no_history: 'No se encontró historial de visitas',
    visit_routine_inspection:
      'Inspección rutinaria de la granja y evaluación de la salud del suelo.',
    visit_next_scheduled: 'Próxima programada',
    action_start_synthesis: 'Iniciar síntesis',
    map_type: 'Tipo de mapa',
    map_legend: 'Leyenda de cultivos',
    map_search_placeholder: 'Buscar agricultores...',
    map_locate_me: 'Localizarme',
    map_reset_view: 'Reiniciar vista',
    map_toggle_stats: 'Alternar estadísticas',
    map_overview: 'Resumen',
    map_farms: 'Granjas',
    map_hectareas: 'Hectáreas',
    map_top_crops: 'Principales cultivos',
    farmer_active_since: 'Activo desde',
    farmer_est_yield: 'Rendimiento est.',
    farmer_farm_size: 'Tamaño de granja',
  },
  de: {
    visits_schedule_new: 'Neuen Besuch planen',
    reports_generate_new: 'Neuen Bericht erstellen',
    reports_description_prefix: 'Umfassende Analyse von ',
    reports_description_suffix: ' Trends und Performance-Metriken für den aktuellen Zeitraum.',
    knowledge_thinking: 'Denkt nach...',
    ai_ask_button: 'KI fragen',
    theme_choose: 'Design wählen',
    theme_select_aesthetic: 'Wählen Sie eine landwirtschaftliche Ästhetik',
    theme_close: 'Schließen',
    usage_init_title: 'Missionskontrolle initialisieren',
    usage_init_desc:
      'Schalten Sie leistungsstarke KI- und SMS-Funktionen frei, indem Sie einen Bereitstellungsplan wählen.',
    usage_realtime_telemetry: 'Echtzeit-Telemetrie',
    usage_critical_threshold: 'Kritischer Schwellenwert',
    action_chat: 'Chat',
    action_sms: 'SMS',
    action_call: 'Anrufen',
    action_video: 'Video',
    farmer_vital_score: 'Vitalitäts-Score',
    visit_no_history: 'Keine Besuchshistorie gefunden',
    visit_routine_inspection:
      'Routinemäßige Farminspektion und Beurteilung der Bodenbeschaffenheit.',
    visit_next_scheduled: 'Nächster Termin',
    action_start_synthesis: 'Synthese starten',
    map_type: 'Kartentyp',
    map_legend: 'Kulturlegende',
    map_search_placeholder: 'Landwirte suchen...',
    map_locate_me: 'Mich lokalisieren',
    map_reset_view: 'Ansicht zurücksetzen',
    map_toggle_stats: 'Stats umschalten',
    map_overview: 'Übersicht',
    map_farms: 'Farmen',
    map_hectares: 'Hektar',
    map_top_crops: 'Top-Kulturen',
    farmer_active_since: 'Aktiv seit',
    farmer_est_yield: 'Geschätzter Ertrag',
    farmer_farm_size: 'Farmgröße',
  },
  en: {
    visits_schedule_new: 'Schedule New Visit',
    reports_generate_new: 'Generate New Report',
    reports_description_prefix: 'Comprehensive analysis of ',
    reports_description_suffix: ' trends and performance metrics for the current period.',
    knowledge_thinking: 'Thinking...',
    ai_ask_button: 'Ask AI',
    theme_choose: 'Choose Theme',
    theme_select_aesthetic: 'Select an agricultural aesthetic',
    theme_close: 'Close',
    usage_init_title: 'Initialize Mission Control',
    usage_init_desc: 'Unlock powerful AI and SMS capabilities by selecting a deployment plan.',
    usage_realtime_telemetry: 'Real-time Telemetry',
    usage_critical_threshold: 'Critical Threshold',
    action_chat: 'Chat',
    action_sms: 'SMS',
    action_call: 'Call',
    action_video: 'Video',
    farmer_vital_score: 'Vital Score',
    visit_no_history: 'No visit history found',
    visit_routine_inspection: 'Routine farm inspection and soil health assessment.',
    visit_next_scheduled: 'Next Scheduled',
    action_start_synthesis: 'Start Synthesis',
    map_type: 'Map Type',
    map_legend: 'Crop Legend',
    map_search_placeholder: 'Search farmers...',
    map_locate_me: 'Locate Me',
    map_reset_view: 'Reset View',
    map_toggle_stats: 'Toggle Stats',
    map_overview: 'Overview',
    map_farms: 'Farms',
    map_hectares: 'Hectares',
    map_top_crops: 'Top Crops',
    farmer_active_since: 'Active Since',
    farmer_est_yield: 'Est. Yield',
    farmer_farm_size: 'Farm Size',
  },
};

languages.forEach(lang => {
  // Find where the language block starts, e.g., "sw: {"
  const lSafe = lang.replace('.', '\\.');
  const startPattern = new RegExp(`^\\s*${lSafe}:\\s*{`, 'm');
  const startMatch = content.match(startPattern);

  if (startMatch) {
    let startIndex = startMatch.index + startMatch[0].length;

    let insertStr = '';
    const source = TRANSLATIONS[lang] || TRANSLATIONS.en;
    for (const [k, v] of Object.entries(source)) {
      // Check if key already exists in this block to avoid double injection
      // We search from startIndex until the closing brace of the block
      // Simple approach: check if k: exist in the whole file if we want to be safe,
      // but better to check only within the block.
      // For now, let's just use the previous "clean-up" logic if we can.

      insertStr += `\n        ${k}: "${v}",`;
    }

    content = content.slice(0, startIndex) + insertStr + content.slice(startIndex);
  }
});

fs.writeFileSync(FILE_PATH, content, 'utf-8');
console.log('Localized strings successfully updated (Revised Logic).');
