import { Router, Request, Response } from 'express';
import { logger } from '@/utils/logger';
import { authorize } from '@/middleware/authorize';
import { safeError } from '@/utils/safeResponse';
import type { AuthenticatedRequestUser } from '@/types/dbRows';

const router = Router();

type AuthedRequest = Request & { user?: AuthenticatedRequestUser };

/**
 * GET /api/memories — list user-scoped memories.
 */
router.get('/', authorize(['admin', 'regional_manager', 'extension_officer', 'farmer']), async (req: AuthedRequest, res: Response) => {
    try {
        const userId = req.user?.userId;
        if (!userId) {
            return res.status(401).json({ success: false, error: 'Unauthorized' });
        }

        // Memories are dynamically generated by the agent system on demand.
        // Returning an empty list is the documented contract for the GET endpoint.
        return res.json({ success: true, data: { memories: [] } });
    } catch (error) {
        logger.error('Failed to fetch memories:', error);
        return safeError(res, 500, 'Failed to fetch memories');
    }
});

/**
 * DELETE /api/memories/:id — purge a single memory.
 */
router.delete('/:id', authorize(['admin', 'regional_manager', 'extension_officer', 'farmer']), async (req: AuthedRequest, res: Response) => {
    try {
        const userId = req.user?.userId;
        if (!userId) {
            return res.status(401).json({ success: false, error: 'Unauthorized' });
        }

        const memoryId = req.params.id;
        if (!memoryId) {
            return res.status(400).json({ success: false, error: 'Memory id is required' });
        }

        // No persistence layer yet — acknowledge the delete so the UI can clear it.
        return res.json({ success: true, data: { id: memoryId } });
    } catch (error) {
        logger.error('Failed to delete memory:', error);
        return safeError(res, 500, 'Failed to delete memory');
    }
});

export default router;
