import { Droplets, Sprout, TrendingUp, AlertTriangle } from 'lucide-react';

export const PdfReportTemplate = () => {
  return (
    <div className="max-w-3xl mx-auto bg-white min-h-[1056px] text-black font-serif shadow-2xl p-12 print:shadow-none print:p-0">
      {/* PDF Header */}
      <header className="border-b-4 border-primary-600 pb-6 mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-4xl font-bold text-gray-900 mb-2">Ag-Extension Advisory Report</h1>
          <p className="text-gray-500 text-sm">Generated by Ag-Extension Decision Support AI</p>
        </div>
        <div className="text-right text-sm text-gray-600">
          <p className="font-bold">Date: October 24, 2026</p>
          <p>Farmer: John Kamau</p>
          <p>Region: Rift Valley Sector 7</p>
        </div>
      </header>

      {/* Main Content Grid */}
      <div className="grid grid-cols-2 gap-8 mb-8">
        
        {/* Left Column */}
        <div className="space-y-8">
          <section>
            <h2 className="text-xl font-bold border-b border-gray-200 pb-2 mb-4 flex items-center gap-2">
              <Sprout size={20} className="text-green-600" /> Crop Status
            </h2>
            <div className="bg-gray-50 p-4 rounded-lg">
              <p className="mb-2"><span className="font-bold">Primary Crop:</span> Maize (Zea mays)</p>
              <p className="mb-2"><span className="font-bold">Growth Stage:</span> Vegetative (V8)</p>
              <p className="mb-2"><span className="font-bold">Est. Yield:</span> 2.4 tons/hectare</p>
              <p><span className="font-bold">Overall Health:</span> Good (NDVI: 0.65)</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold border-b border-gray-200 pb-2 mb-4 flex items-center gap-2">
              <Droplets size={20} className="text-blue-600" /> Soil & Weather
            </h2>
            <div className="bg-gray-50 p-4 rounded-lg">
              <p className="mb-2"><span className="font-bold">Current Moisture:</span> 38% (Slightly Low)</p>
              <p className="mb-2"><span className="font-bold">7-Day Rainfall:</span> 12mm recorded</p>
              <p><span className="font-bold">Forecast:</span> 60% chance of rain on Thursday.</p>
            </div>
          </section>
        </div>

        {/* Right Column */}
        <div className="space-y-8">
          <section>
            <h2 className="text-xl font-bold border-b border-gray-200 pb-2 mb-4 flex items-center gap-2">
              <AlertTriangle size={20} className="text-red-600" /> Actionable Alerts
            </h2>
            <div className="bg-red-50 border border-red-100 p-4 rounded-lg text-red-900">
              <h3 className="font-bold mb-2">Nitrogen Deficiency Warning</h3>
              <p className="text-sm">
                Satellite spectral analysis indicates a drop in chlorophyll levels in the north quadrant. 
                <strong> Recommended Action:</strong> Apply top-dressing fertilizer within the next 4 days before the forecasted rain.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold border-b border-gray-200 pb-2 mb-4 flex items-center gap-2">
              <TrendingUp size={20} className="text-emerald-600" /> Market Snapshot
            </h2>
            <div className="bg-gray-50 p-4 rounded-lg">
              <table className="w-full text-sm text-left">
                <thead>
                  <tr className="border-b border-gray-300">
                    <th className="pb-2">Commodity</th>
                    <th className="pb-2">Price/90kg</th>
                    <th className="pb-2">Trend</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-gray-200">
                    <td className="py-2">Maize (Dry)</td>
                    <td className="py-2">KES 3,200</td>
                    <td className="py-2 text-red-600">▼ 5%</td>
                  </tr>
                  <tr>
                    <td className="py-2">Beans (Rosecoco)</td>
                    <td className="py-2">KES 8,500</td>
                    <td className="py-2 text-green-600">▲ 2%</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>
        </div>
      </div>

      {/* AI Summary Section */}
      <section className="bg-primary-50 p-6 rounded-xl border border-primary-100">
        <h2 className="text-lg font-bold text-primary-900 mb-2">AI Advisory Summary</h2>
        <p className="text-primary-800 leading-relaxed text-sm">
          Based on the data collected this week, your farm is performing well but faces a slight risk of nutrient stress. 
          Focus on applying nitrogen-rich fertilizers to the north quadrant to capitalize on the upcoming rain. 
          Given the current drop in maize prices, consider holding your harvested stock for an additional 3 weeks if storage permits, 
          as historical data suggests a price rebound in late November.
        </p>
      </section>

      {/* Footer */}
      <footer className="mt-12 pt-6 border-t border-gray-200 text-center text-xs text-gray-500">
        <p>This report is generated by an AI assistant and should be used as a supplementary tool for decision making.</p>
        <p className="mt-1">© 2026 Ag-Extension Decision Support | Support Hotline: *800#</p>
      </footer>
    </div>
  );
};
