import {
  LayoutDashboard,
  MessageSquare,
  Users,
  UserPlus,
  Sparkles,
  MapPin,
  FileText,
  Send,
  BarChart3,
  CreditCard,
  Activity,
  Settings,
  Shield,
  Leaf,
  Brain,
  Mail,
  Wrench,
  Search,
  UserCog,
  Globe,
} from 'lucide-react';

export interface NavItem {
  id: string;
  label: string;
  labelKey?: string;
  icon: React.ComponentType<{ className?: string }>;
  roles: string[];
  /** When true, this nav item is hidden for demo users */
  hiddenInDemo?: boolean;
  /** When true, this feature requires a Pro or Enterprise subscription tier */
  requiresPro?: boolean;
}

export const getNavItems = (): NavItem[] => [
  {
    id: 'dashboard',
    label: 'Dashboard',
    labelKey: 'nav_dashboard',
    icon: LayoutDashboard,
    roles: ['extension_officer', 'admin'],
  },
  {
    id: 'farmer_dashboard',
    label: 'Dashboard',
    labelKey: 'nav_dashboard',
    icon: LayoutDashboard,
    roles: ['farmer'],
  },
  {
    id: 'aiassistant',
    label: 'AI Assistant',
    labelKey: 'nav_aiassistant',
    icon: MessageSquare,
    roles: ['extension_officer', 'admin', 'farmer'],
    hiddenInDemo: true,
    requiresPro: true,
  },
  {
    id: 'farmerchat',
    label: 'Farmer Chat',
    labelKey: 'nav_farmerchat',
    icon: Users,
    roles: ['extension_officer', 'admin'],
    requiresPro: true,
  },
  {
    id: 'knowledge',
    label: 'Knowledge Base',
    labelKey: 'nav_knowledge',
    icon: Search,
    roles: ['extension_officer', 'admin', 'farmer'],
  },
  {
    id: 'portfolio',
    label: 'Farmers',
    labelKey: 'nav_farmers',
    icon: Users,
    roles: ['extension_officer', 'admin'],
  },
  {
    id: 'register_farmer',
    label: 'Register Client',
    labelKey: 'nav_register_farmer',
    icon: UserPlus,
    roles: ['extension_officer', 'admin'],
  },
  {
    id: 'visit_synthesis',
    label: 'Visit Synthesis',
    labelKey: 'nav_visit_synthesis',
    icon: Sparkles,
    roles: ['extension_officer', 'admin'],
    requiresPro: true,
  },
  {
    id: 'visits',
    label: 'Visits',
    labelKey: 'nav_visits',
    icon: MapPin,
    roles: ['extension_officer', 'admin', 'farmer'],
    requiresPro: true,
  },
  {
    id: 'reports',
    label: 'Reports',
    labelKey: 'nav_reports',
    icon: FileText,
    roles: ['extension_officer', 'admin'],
  },
  {
    id: 'sms',
    label: 'SMS',
    labelKey: 'nav_sms',
    icon: Send,
    roles: ['extension_officer', 'admin'],
    requiresPro: true,
  },
  {
    id: 'analytics',
    label: 'Analytics',
    labelKey: 'nav_analytics',
    icon: BarChart3,
    roles: ['extension_officer', 'admin'],
    requiresPro: true,
  },
  {
    id: 'billing',
    label: 'Billing',
    labelKey: 'nav_billing',
    icon: CreditCard,
    roles: ['extension_officer', 'admin', 'farmer'],
  },
  {
    id: 'telemetry',
    label: 'Telemetry',
    labelKey: 'nav_telemetry',
    icon: Activity,
    roles: ['admin'],
  },
  {
    id: 'agents',
    label: 'Agents',
    labelKey: 'nav_agents',
    icon: Settings,
    roles: ['admin'],
  },
  {
    id: 'system_health',
    label: 'System Health',
    labelKey: 'nav_system_health',
    icon: Shield,
    roles: ['admin'],
  },
  {
    id: 'fields',
    label: 'Fields',
    labelKey: 'nav_fields',
    icon: Leaf,
    roles: ['extension_officer', 'admin', 'farmer'],
  },
  {
    id: 'disease_diagnosis',
    label: 'Disease Diagnosis',
    labelKey: 'nav_disease_diagnosis',
    icon: Leaf,
    roles: ['extension_officer', 'admin'],
    requiresPro: true,
  },
  {
    id: 'memory',
    label: 'Memory',
    labelKey: 'nav_memory',
    icon: Brain,
    roles: ['admin'],
  },
  {
    id: 'email_workflows',
    label: 'Email Workflows',
    labelKey: 'nav_email_workflows',
    icon: Mail,
    roles: ['admin'],
    requiresPro: true,
  },
  {
    id: 'mcp_tools',
    label: 'MCP Tools',
    labelKey: 'nav_mcp_tools',
    icon: Wrench,
    roles: ['admin'],
  },
  {
    id: 'user_management',
    label: 'User Management',
    labelKey: 'nav_user_management',
    icon: UserCog,
    roles: ['admin'],
  },
  {
    id: 'worldmonitor',
    label: 'WorldMonitor',
    labelKey: 'nav_worldmonitor',
    icon: Globe,
    roles: ['extension_officer', 'admin', 'regional_manager'],
    requiresPro: true,
  },
];
